# Generated by Django 3.1.2 on 2020-10-16 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=256)),
                ('student', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.studentdata')),
            ],
        ),
    ]
